//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proga.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("password=qwerty;persistsecurityinfo=True;user id=root;server=localhost;database=r" +
            "ostelecom4")]
        public string rostelecom4ConnectionString {
            get {
                return ((string)(this["rostelecom4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int menu {
            get {
                return ((int)(this["menu"]));
            }
            set {
                this["menu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 250, 255")]
        public global::System.Drawing.Color BackColorMain {
            get {
                return ((global::System.Drawing.Color)(this["BackColorMain"]));
            }
            set {
                this["BackColorMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11, 11, 11")]
        public global::System.Drawing.Color ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ForeColor"]));
            }
            set {
                this["ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MintCream")]
        public global::System.Drawing.Color BackColorGroup {
            get {
                return ((global::System.Drawing.Color)(this["BackColorGroup"]));
            }
            set {
                this["BackColorGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LavenderBlush")]
        public global::System.Drawing.Color ButtonBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackColor"]));
            }
            set {
                this["ButtonBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11, 11, 11")]
        public global::System.Drawing.Color GridForeColor {
            get {
                return ((global::System.Drawing.Color)(this["GridForeColor"]));
            }
            set {
                this["GridForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LavenderBlush")]
        public global::System.Drawing.Color GridBackColor {
            get {
                return ((global::System.Drawing.Color)(this["GridBackColor"]));
            }
            set {
                this["GridBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightPink")]
        public global::System.Drawing.Color GridSelColor {
            get {
                return ((global::System.Drawing.Color)(this["GridSelColor"]));
            }
            set {
                this["GridSelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GridCellsColor {
            get {
                return ((global::System.Drawing.Color)(this["GridCellsColor"]));
            }
            set {
                this["GridCellsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Theme {
            get {
                return ((int)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color ButtonBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBorderColor"]));
            }
            set {
                this["ButtonBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightPink")]
        public global::System.Drawing.Color ButtonDown {
            get {
                return ((global::System.Drawing.Color)(this["ButtonDown"]));
            }
            set {
                this["ButtonDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MistyRose")]
        public global::System.Drawing.Color ButtonOver {
            get {
                return ((global::System.Drawing.Color)(this["ButtonOver"]));
            }
            set {
                this["ButtonOver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color GridAlter {
            get {
                return ((global::System.Drawing.Color)(this["GridAlter"]));
            }
            set {
                this["GridAlter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int saveuser {
            get {
                return ((int)(this["saveuser"]));
            }
            set {
                this["saveuser"] = value;
            }
        }
    }
}
